### ISSUE TITLE
Change icon for Quick settings

### ISSUE THREAD

**Issue by KaustubhPatange** [Patil-Tanmay/QuickAccess#2]
When user set an app for quick access, set the icon of the app.

**Comment by Patil-Tanmay** [comment]
Thanks For the Suggestion but here is the issue I faced with this feature request.

I implemented this feature but icons are complex drawable which is not suitable for tile service icon. So Even if we set these icon for tile service, it will only show black or empty icon in Tile Service. 
So Instead of changing Icon, I am changing the label in the tile service.
